matrix:
  include:
  - language: node_js
    cache:
      directories:
        - client/node_modules
    node_js:
      - 10
    os:
      - linux
    before_install: cd client
    install: npm install
    script:
      - npm run ci:build
      # - npm run test
    before_deploy: npm install now --no-save
    deploy:
      - provider: script
        script: cp ../now.json build/now.json && now --token $NOW_TOKEN build && now alias --token $NOW_TOKEN staging.rtop.khoanguyen.me
        skip_cleanup: true
        on:
          now-test: true
