version: '3.6'
services:
  postgres:
    image: postgres
    ports:
    - "5432:5432"
    environment:
    - "POSTGRES_PASSWORD:mysecretpassword"
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-alpha11
    ports:
    - "8081:8080"
    depends_on:
    - postgres
    restart: always
    environment:
    - POSTGRES_PASSWORD:mysecretpassword
    command: >
      /bin/sh -c "
      graphql-engine 
      --database-url postgres://postgres:$${POSTGRES_PASSWORD}@postgres:5432/postgres 
      serve --enable-console;"
      # --access-key mysecretkey 
volumes:
  db_data:
